# Generated by Django 3.1.7 on 2021-05-10 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='subCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(verbose_name='subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('desp', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('gst', models.CharField(choices=[('5', '5'), ('12', '12'), ('15', '15'), ('18', '18')], default='18', max_length=5)),
                ('discount_per', models.DecimalField(decimal_places=0, default=5, max_digits=2)),
                ('img', models.ImageField(blank=True, null=True, upload_to='uploads/products/')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='uploads/products/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='uploads/products/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='uploads/products/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/products/')),
                ('dateadded', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.CharField(max_length=4)),
                ('edition', models.CharField(default='2018', max_length=4)),
                ('medium', models.CharField(choices=[('English', 'English'), ('Marathi', 'Marathi'), ('Hindi', 'Hindi'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts')], default='', max_length=10)),
                ('label', models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=1)),
                ('instock', models.BooleanField(default=True)),
                ('isExchnageable', models.BooleanField(default=True)),
                ('isReturnable', models.BooleanField(default=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.category')),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.subcategory')),
            ],
        ),
    ]
