# Generated by Django 3.1.7 on 2021-07-25 12:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeban', models.ImageField(blank=True, null=True, upload_to='uploads/products/')),
                ('homeban1', models.ImageField(blank=True, null=True, upload_to='uploads/products/')),
                ('homeban2', models.ImageField(blank=True, null=True, upload_to='uploads/products/')),
                ('homeban3', models.ImageField(blank=True, null=True, upload_to='uploads/products/')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(verbose_name='category')),
                ('cat_ban', models.ImageField(blank=True, null=True, upload_to='uploads/Category/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('desp', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('gst', models.CharField(choices=[('0', '0'), ('5', '5'), ('7', '7'), ('12', '12'), ('15', '15'), ('18', '18'), ('22', '22'), ('24', '24'), ('28', '28')], default='18', max_length=5)),
                ('discount_per', models.DecimalField(decimal_places=0, default=5, max_digits=2)),
                ('img', models.ImageField(blank=True, null=True, upload_to='uploads/products/')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='uploads/products/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='uploads/products/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='uploads/products/')),
                ('dateadded', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.CharField(max_length=4)),
                ('edition', models.CharField(default='2018', max_length=4)),
                ('medium', models.CharField(choices=[('NEET', 'NEET'), ('JEE', 'JEE'), ('CET', 'CET'), ('English', 'English'), ('Marathi', 'Marathi'), ('Hindi', 'Hindi'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts'), ('Notebooks', 'Notebooks'), ('Stationary', 'Stationary'), ('Story Books', 'Story Books'), ('Biography', 'Biography'), ('F.Y', 'First Year'), ('S.Y', 'Second Year'), ('T.Y', 'Third Year')], default='', max_length=20)),
                ('label', models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=1)),
                ('instock', models.BooleanField(default=True)),
                ('isExchnageable', models.BooleanField(default=True)),
                ('isReturnable', models.BooleanField(default=True)),
                ('isBestSeller', models.BooleanField(default=False)),
                ('isDealoftheday', models.BooleanField(blank=True, default=False, null=True)),
                ('isBindable', models.BooleanField(default=False)),
                ('isBinding', models.BooleanField(default=False)),
                ('bind_price', models.DecimalField(decimal_places=2, default=30.0, max_digits=6)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.category')),
            ],
        ),
        migrations.CreateModel(
            name='Refund_bankdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipent_name', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=15)),
                ('ifsc_code', models.CharField(max_length=10)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refund_upidetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipent_name', models.CharField(max_length=20)),
                ('recipent_upi_id', models.CharField(max_length=15)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requestbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('book_type', models.CharField(choices=[('1', 'Textbook'), ('2', 'Reference book'), ('3', 'Study material'), ('4', 'Novel'), ('5', 'Story books/Biography'), ('6', 'Others')], default='', max_length=10)),
                ('book_relatedto', models.CharField(choices=[('1', 'State Board'), ('2', 'CBSE Board'), ('3', 'Study ICSE Board'), ('4', 'Entrance exams'), ('5', 'For book readers'), ('6', 'Others')], default='', max_length=10)),
                ('book_desp', models.TextField()),
                ('book_img', models.ImageField(blank=True, null=True, upload_to='uploads/Request/')),
                ('book_required', models.CharField(max_length=10, null=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('author_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_phone', models.IntegerField(blank=True, null=True)),
                ('customer_mail_id', models.EmailField(max_length=254)),
                ('ispriority', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='subCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(verbose_name='subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.product')),
                ('userx', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.wishlist')),
            ],
        ),
        migrations.AddField(
            model_name='wishlist',
            name='Products',
            field=models.ManyToManyField(through='Ecom.WishlistProduct', to='Ecom.Product'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductUnavailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_mail_id', models.EmailField(max_length=254)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('Products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.subcategory'),
        ),
        migrations.CreateModel(
            name='EcomOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.IntegerField(default=0)),
                ('order_total', models.IntegerField(default=100)),
                ('order_price', models.IntegerField(default=100)),
                ('payment_mode', models.CharField(choices=[('1', 'Online Payment'), ('2', 'Cash Payment')], default='Cash Payment', max_length=20)),
                ('products', models.TextField(default='')),
                ('address', models.CharField(default='', max_length=100)),
                ('order_completed', models.BooleanField(default=False)),
                ('date_of_ordering', models.DateField(default=datetime.date.today)),
                ('date_of_delivery', models.DateField(default=datetime.date(2021, 8, 1))),
                ('gift_message', models.TextField(blank=True, default='', null=True)),
                ('gift_from', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('order_status', models.CharField(choices=[('1', 'Order Created'), ('2', 'Order Packed'), ('3', 'Out for Delivery'), ('4', 'Order delivery Pending'), ('5', 'Delivered'), ('6', 'Order Cancelled'), ('7', 'Exchange Requested'), ('8', 'Return Requested'), ('9', 'Exchange Approved'), ('10', 'Return Approved'), ('11', 'Refund Intiated'), ('12', 'ReFunded Succesfully')], default='Order Created', max_length=20)),
                ('Order_placed_BY', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_placed_by_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quan', models.IntegerField(default=1)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.product')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.cart')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='Products',
            field=models.ManyToManyField(through='Ecom.CartProduct', to='Ecom.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
