# Generated by Django 3.1.7 on 2021-08-22 14:23

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomorder',
            name='contact_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ecomorder',
            name='contact_no',
            field=models.CharField(default=9999988888, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ecomorder',
            name='date_of_delivery',
            field=models.DateField(default=datetime.date(2021, 8, 29)),
        ),
    ]
