# Generated by Django 3.1.7 on 2021-04-18 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='medium',
            field=models.CharField(choices=[('English', 'English'), ('Marathi', 'Marathi'), ('Hindi', 'Hindi'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('Textbooks', 'Textbooks'), ('Digest', 'Digest'), ('21 Sets', '21 sets'), ('Combo', 'combo'), ('biograhy', 'biograhy'), ('storyteller', 'storyteller'), ('Helping Hand', 'Helping Hnad')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ecom.category'),
            preserve_default=False,
        ),
    ]
