# Generated by Django 3.1.7 on 2021-08-24 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0003_auto_20210822_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecomorder',
            name='date_of_delivery',
            field=models.DateField(default=datetime.date(2021, 8, 29)),
        ),
        migrations.AlterField(
            model_name='ecomorder',
            name='order_status',
            field=models.CharField(choices=[('1', 'Order Created'), ('2', 'Order Packed'), ('3', 'Out for Delivery'), ('4', 'Order delivery Pending'), ('5', 'Delivered'), ('6', 'Order Cancelled'), ('7', 'Order Completed'), ('8', 'Exchange Requested'), ('9', 'Return Requested'), ('10', 'Exchange Approved'), ('11', 'Return Approved'), ('12', 'Refund Intiated'), ('13', 'ReFunded Succesfully'), ('14', 'Exchanged Successfully')], default='Order Created', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='medium',
            field=models.CharField(choices=[('NEET', 'NEET'), ('JEE', 'JEE'), ('CET', 'CET'), ('English', 'English'), ('Marathi', 'Marathi'), ('Hindi', 'Hindi'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts'), ('Notebooks', 'Notebooks'), ('Stationary', 'Stationary'), ('Story Books', 'Story Books'), ('Biography', 'Biography'), ('First Year', 'First Year'), ('S.Y', 'Second Year'), ('T.Y', 'Third Year')], default='', max_length=20),
        ),
    ]
