# Generated by Django 3.1.7 on 2021-08-26 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0004_auto_20210824_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecomorder',
            name='date_of_delivery',
            field=models.DateField(default=datetime.date(2021, 8, 31)),
        ),
        migrations.AlterField(
            model_name='product',
            name='medium',
            field=models.CharField(choices=[('NEET', 'NEET'), ('JEE', 'JEE'), ('CET', 'CET'), ('English', 'English'), ('Marathi', 'Marathi'), ('Hindi', 'Hindi'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts'), ('Notebooks', 'Notebooks'), ('Stationary', 'Stationary'), ('Story Books', 'Story Books'), ('Biography', 'Biography'), ('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year')], default='', max_length=20),
        ),
    ]
