# Generated by Django 3.1.7 on 2021-10-05 13:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0005_auto_20210826_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund_bankdetails',
            name='return_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='refund_upidetails',
            name='return_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ecomorder',
            name='date_of_delivery',
            field=models.DateField(default=datetime.date(2021, 10, 10)),
        ),
        migrations.CreateModel(
            name='Exchange_return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('1', 'Return'), ('2', 'Exchnage')], max_length=20)),
                ('reason', models.CharField(choices=[('1', 'Poor product quality'), ('2', 'Product received is damaged'), ('3', 'Product & Shipping box both are damaged'), ('4', 'Product received is different'), ('5', 'Other')], max_length=20)),
                ('comment', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.ecomorder')),
            ],
        ),
    ]
