# Generated by Django 3.1.7 on 2021-09-25 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0005_auto_20210826_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='gift_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='gift_from',
            field=models.CharField(default='  ', max_length=20),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='gift_message',
            field=models.CharField(default='  ', max_length=255),
        ),
        migrations.AlterField(
            model_name='ecomorder',
            name='date_of_delivery',
            field=models.DateField(default=datetime.date(2021, 10, 1)),
        ),
    ]
