# Generated by Django 3.1.7 on 2021-04-18 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_name',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
