# Generated by Django 3.1.7 on 2021-09-27 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0007_merge_20210927_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ecomorder',
            name='date_of_delivery',
            field=models.DateField(default=datetime.date(2021, 10, 2)),
        ),
    ]
