# Generated by Django 3.1.7 on 2021-10-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0009_exchange_return_orderplacedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund_bankdetails',
            name='refund_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refund_upidetails',
            name='refund_completed',
            field=models.BooleanField(default=False),
        ),
    ]
