# Generated by Django 3.1.7 on 2021-10-13 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0009_auto_20211010_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='gift_from',
            field=models.CharField(default='  ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='gift_message',
            field=models.CharField(default='  ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ecomorder',
            name='date_of_delivery',
            field=models.DateField(default=datetime.date(2021, 10, 18)),
        ),
    ]
