# Generated by Django 3.1.7 on 2021-10-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0010_auto_20211013_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='gift_from',
            field=models.CharField(blank=True, default='  ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='gift_message',
            field=models.CharField(blank=True, default='  ', max_length=255, null=True),
        ),
    ]
