# Generated by Django 3.1.7 on 2021-10-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0010_auto_20211005_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund_bankdetails',
            name='refund_completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='refund_upidetails',
            name='refund_completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
