# Generated by Django 3.1.7 on 2021-10-16 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0012_auto_20211010_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecomorder',
            name='date_of_delivery',
            field=models.DateField(default=datetime.date(2021, 10, 21)),
        ),
    ]
