# Generated by Django 3.1.7 on 2022-02-03 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0011_auto_20211013_1426'),
        ('Ecom', '0013_auto_20211016_1652'),
    ]

    operations = [
    ]
