# Generated by Django 3.1.7 on 2021-05-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='addpincode',
            field=models.DecimalField(decimal_places=0, default=421501, max_digits=6),
            preserve_default=False,
        ),
    ]
