# Generated by Django 3.1.7 on 2021-05-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_address_addpincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='pincode',
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
