# Generated by Django 3.1.7 on 2021-05-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20210516_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Cust_Name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
