# Generated by Django 3.1.7 on 2021-06-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_auto_20210608_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='isdeafault',
            field=models.BooleanField(default=False),
        ),
    ]
