# Generated by Django 3.1.7 on 2021-06-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_address_isdeafault'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailid', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=4)),
                ('is_verfied', models.BooleanField(default=False)),
            ],
        ),
    ]
