# Generated by Django 3.1.7 on 2021-07-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_customer_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
