# Generated by Django 3.1.7 on 2021-07-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_address_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.IntegerField(default=7756078806),
        ),
    ]
