# Generated by Django 3.1.7 on 2021-07-09 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_auto_20210709_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='phone_number',
            new_name='number',
        ),
    ]
