# Generated by Django 3.1.7 on 2021-07-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0017_auto_20210721_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('HD', 'Half Day')], default='A', max_length=2),
        ),
    ]
