# Generated by Django 3.1.7 on 2021-07-21 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0018_auto_20210721_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='emp_id',
            field=models.ForeignKey(default=1, limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
