# Generated by Django 3.1.7 on 2021-10-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0020_auto_20211016_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMAlE'), ('O', 'Other')], default='Other', max_length=8),
        ),
    ]
