# Generated by Django 3.1.7 on 2021-06-10 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ecom', '0020_auto_20210610_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giftmessage', models.TextField(blank=True, null=True)),
                ('giftmessage_from', models.CharField(blank=True, max_length=254, null=True)),
                ('ordercreated_time', models.DateTimeField(auto_now=True)),
                ('orderstatus', models.CharField(choices=[('1', 'Order placed'), ('2', 'Order  Shipping'), ('3', 'Order Dispatched'), ('4', 'Order Out For Delivery'), ('5', 'Order Delivery'), ('6', 'Order Cancelled')], default='1', max_length=15)),
                ('payment', models.CharField(choices=[('1', 'Order placed'), ('2', 'Order  Shipping'), ('3', 'Order Dispatched'), ('4', 'Order Out For Delivery'), ('5', 'Order Delivery'), ('6', 'Order Cancelled')], default='1', max_length=15)),
                ('order_mrp', models.IntegerField(blank=True, null=True)),
                ('order_saving', models.IntegerField(blank=True, null=True)),
                ('order_delivery', models.IntegerField(blank=True, null=True)),
                ('no_of_product', models.IntegerField(blank=True, null=True)),
                ('coupons_discount', models.IntegerField(blank=True, null=True)),
                ('order_total_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderstatus', models.CharField(choices=[('1', 'Return'), ('2', 'Exchange')], default='1', max_length=15)),
                ('orderReturn_time', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='orderReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_return_status', models.CharField(choices=[('1', 'Return'), ('2', 'Exchange')], default='1', max_length=15)),
                ('orderstatus', models.CharField(choices=[('1', 'Order placed'), ('2', 'Order  Shipping'), ('3', 'Order Dispatched'), ('4', 'Order Out For Delivery'), ('5', 'Order Delivery'), ('6', 'Order Cancelled')], default='1', max_length=15)),
                ('returnReason', models.TextField(blank=True, null=True)),
                ('orderReturn_time', models.DateTimeField(auto_now=True)),
                ('return_prodimg', models.ImageField(blank=True, null=True, upload_to='uploads/returnProducts/')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quan', models.IntegerField(default=1)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Products',
            field=models.ManyToManyField(through='orders.OrderProduct', to='Ecom.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
