# Generated by Django 3.1.7 on 2021-06-10 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_pincode'),
        ('orders', '0002_order_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_id',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, to='Accounts.address'),
        ),
    ]
